### ISSUE TITLE
Installing unnecessary modules

### ISSUE THREAD

**Issue by YanivSa** [slushjs/gulp-install#16]
First of all, very useful package; Good work :+1: 

The issue:
When the program list "dependent modules", it treats commented require-s statements, and JSON loading processes ("require('./list.json')") as dependent packages - this shouldn't happen.

**Comment by joakimbeng** [comment]
This plugin does not look at your code at all.
The plugin only looks for a package.json or a bower.json in the piped stream and calls `npm install` or `bower install` accordingly.
