### ISSUE TITLE
add option to pass location of npm repo

### ISSUE THREAD

**Issue by freeranger** [slushjs/gulp-install#19]
Hi,

It would be great if we could pass this in - I work in an corporate environment behind a firewall so we can't access the real npm repo and instead have an internal proxy,

I can pass the repo to npm on the command line....it would be very useful to be able to specify this for gulp-install too.

**Comment by jwulf** [comment]
You can do that by running something like:

npm set registry "http://registry.npmjs.org"

**Comment by joakimbeng** [comment]
Use the new [`args`](https://github.com/slushjs/gulp-install#optionsargs) option for this. (thanks to #29)
