### ISSUE TITLE
support jspm install

### ISSUE THREAD

**Issue by osdevisnot** [slushjs/gulp-install#23]
please support [jspm](http://jspm.io/) install through command `jspm install`

**Comment by kosz** [comment]
(y) 

@joakimbeng how do you feel about this feature ?

**Comment by kosz** [comment]
well here's a PR. I'd love to see this in for various slush generators i'm working on which use jspm. let me know if there's other things i should improve on the PR. 

https://github.com/slushjs/gulp-install/pull/25

**Comment by nevercast** [comment]
:+1: I'm going to go ahead and use that PR in my project. I require npm, bower and JSPM in my Aurelia project and this makes it smoother. Cheers @kosz
