### ISSUE TITLE
Support passing arguments to npm install

### ISSUE THREAD

**Issue by peterjuras** [slushjs/gulp-install#28]
Currently gulp-install only supports a few arguments like --production and --ignore-scripts.

It would be helpful to have a generic option like "args" to pass in other arguments that are supported by npm install.

**Comment by crkepler** [comment]
+1
Is there currently a **work-around** for this? 

Case in point, I need to pass in `--msvs_version=2013` for some of my clients with Windows (node-gyp). 
E.g.: `npm install --msvs_version=2013`

Any suggestions?

**Comment by peterjuras** [comment]
Check my pull request, you can use my version in the time being.


Sent by Outlook for Android





On Wed, Sep 30, 2015 at 9:14 AM -0700, "crkepler" <notifications@github.com> wrote:
+1
Is there currently a **work-around** for this?

Case in point, I need to pass in `--msvs_version=2013` for some of my clients with Windows (node-gyp).
E.g.: `npm install --msvs_version=2013`

Any suggestions?

---

**Comment by crkepler** [comment]
@peterjuras : It works perfectly!!! 

This is exactly what I was looking for. Great work, thanks for your help on this.
