### ISSUE TITLE
Support passing configuration data (package.json, bower.json, ...) as object or string instead of using additional external configuration files

### ISSUE THREAD

**Issue by alp82** [slushjs/gulp-install#30]
Currently it's not possible to have a single-file configuration for frontend projects. If you use gulp and need package management, you have at least two configuration files.

What about passing a Javascript object to gulp-install instead of referencing an external file?

It could look like this:

    {
      "package.json": {
        "name": "my-project",
        "version": "1.0.0",
        "author": "Your Name <your.name@example.org>",
        "license": "MIT"
      },
      "requirements.txt": [
        "some-framework==0.9.4",
        "another-library>=0.2"
      ]
    }

**Comment by tipok** [comment]
+1

**Comment by joakimbeng** [comment]
-1

If you want to create virtual files like that I recommend creating those with [vinyl](https://github.com/gulpjs/vinyl) and piping them to `gulp-install`.
