### ISSUE TITLE
TSD is deprecated. Can you add Typings?

### ISSUE THREAD

**Issue by codeBelt** [slushjs/gulp-install#37]
Check out https://github.com/Definitelytyped/tsd and you will see it says:

"**DEPRECATED: TSD is deprecated, please use [Typings](http://github.com/typings/typings) and see [this issue](https://github.com/DefinitelyTyped/tsd/issues/269) for more information.**"

Can you please add `typings install` to install modules from `typings.json` to be installed?
https://github.com/typings/typings

**Comment by rcollette** [comment]
or just just use gulp-typings
