### ISSUE TITLE
Support silent npm install

### ISSUE THREAD

**Issue by balassy** [slushjs/gulp-install#44]
I've using this package to do `npm install`, and I would like to run it without displaying the summary at the end of the run. I've tried to add `--silent` and `--quiet` to the `args` option, but the summary of the installed packages are always written to the output.

Thanks for creating and maintaining this package!

**Comment by joakimbeng** [comment]
It's now possible to pass any argument to `npm` like so:

```js
gulp.src('...').pipe(install({
  npm: ['--any', '--arg', 'and', 'more']
}))
```

I don't know how to completely turn of the npm output, but maybe the loglevel option is an alternative? (which is not possible to specify)

**Comment by balassy** [comment]
Thank you, Joakim!
