### ISSUE TITLE
Args parsing always prepends "--" to arg name, breaks commands like "--argname foo"

### ISSUE THREAD

**Issue by cboscolo** [slushjs/gulp-install#45]
I'm trying to call install like this:
`    .pipe(install({production: true, args: ['--registry', 'https://npm-proxy.fury.io/foobar/'}));
`
doesn't work because gulp-install turn 'https://npm-proxy.fury.io/foobar/' into '--https://npm-proxy.fury.io/foobar/'.

Can this auto-prepend of '--' to args be removed?

**Comment by joakimbeng** [comment]
Yes!
A fix is on its way!
(sorry for the slow response)
